typography_spectrum: 0.5074737260583788
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7018983715679497
  lightness: 0.19896871969103813
  saturation: 0.4302034985739738
  rhythmicContrast: 0.39919875375926495
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6186132631264627
analytics:
  google: null
  facebook: null
  twitter: null
name: taroerunas
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
